# Generated by Django 3.2.8 on 2021-11-18 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('ats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpon.ats')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('template', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpon.olt')),
            ],
        ),
        migrations.CreateModel(
            name='Rssi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rx', models.FloatField(blank=True, null=True)),
                ('tx', models.FloatField(blank=True, null=True)),
                ('ont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpon.ont')),
            ],
        ),
    ]
