# Generated by Django 3.2.8 on 2021-11-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='ats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olts', to='gpon.ats'),
        ),
        migrations.AlterField(
            model_name='ont',
            name='olt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onts', to='gpon.olt'),
        ),
        migrations.AlterField(
            model_name='rssi',
            name='ont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rssi', to='gpon.ont'),
        ),
    ]
