# Generated by Django 3.2.8 on 2021-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ont',
            name='serial',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
